### ISSUE TITLE
 "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by Stajor** [laminas/laminas-stdlib#57]
"laminas/laminas-stdlib": "~2.5"
php: 8.0

Error:
```
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? {"exception":"[object] (ErrorException(code: 0): \"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? at vendor/laminas/laminas-stdlib/src/ArrayObject.php:425)
```

Trace:
```
#4 vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php(107): Composer\\Autoload\\ClassLoader->loadClass()
#5 vendor/laminas/laminas-stdlib/src/Parameters.php(28): Laminas\\ZendFrameworkBridge\\Autoloader::Laminas\\ZendFrameworkBridge\\{closure}()
#6 vendor/laminas/laminas-http/src/Request.php(272): Laminas\\Stdlib\\Parameters->__construct()
#7 vendor/laminas/laminas-http/src/Client.php(838): Laminas\\Http\\Request->getQuery()
#8 vendor/laminas/laminas-oauth/library/Laminas/OAuth/Http.php(271): Laminas\\Http\\Client->send()
#9 vendor/laminas/laminas-oauth/library/Laminas/OAuth/Http.php(156): Laminas\\OAuth\\Http->_attemptRequest()
#10 vendor/laminas/laminas-oauth/library/Laminas/OAuth/Http/RequestToken.php(37): Laminas\\OAuth\\Http->startRequestCycle()
#11 vendor/laminas/laminas-oauth/library/Laminas/OAuth/Consumer.php(84): Laminas\\OAuth\\Http\\RequestToken->execute()
```

**Comment by Ocramius** [comment]
`laminas-stdlib` is on `3.x` since ages: please upgrade.
